### ISSUE TITLE
[Bug]: Garbled code exists when using Chinese in request body of external integration configuration

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1624]
### ODC version

4.2.4

### OB version

any

### What happened?

When I create a external integration config such as:
```yaml
approvalTimeoutSeconds: 86400
http:
  connectTimeoutSeconds: 5
  socketTimeoutSeconds: 30
api:
  start:
    # Request method, supported values: GET | POST | PUT | PATCH
    method: POST
    # Request URI
    url: http://localhost:45678/start
    # Request headers, the format is: <key: value>
    headers:
      # Sample of headers
      Content-Type: application/json;charset=UTF-8
      Accept: application/json
    # Request query parameters, the format is: <key: value>
    queryParameters: ~
    # Request body
    body:
      # Type of request body, supported values: FORM_DATA | RAW
      type: RAW
      # Content of request body, the format is: <String> for RAW type or <key: value> for FORM_DATA type
      # Sample of request content in type of RAW
      content: |-
        {
          "userId": "${user.id}",
          "riskLevel": "高风险",  # using Chinese
          "userName": "${user.account}",
          "taskType": "${task.type}",
          "connection": "${connection.name}",
          "tenant": "${connection.tenant}",
          "sqlContent": "${sql.content}",
          "taskDetails": "${task.details}"

        }
    # Mark whether the request body is encrypted
    requestEncrypted: false
    # Expression to judge whether the request is successful based on the response body analysis, using the SPEL syntax
    requestSuccessExpression: '[success] == true'
    # Mark whether the response body is encrypted
    responseEncrypted: false
    # Expression to extract ID of process instance created by the external system based on the response body analysis, using the SPEL syntax
    extractInstanceIdExpression: '[content][processInstanceId]'
```
Then the actual request body exists garbled code such as:
<img width="1513" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/dd82783c-1e3a-41bd-9804-1f0520b15385">

### What did you expect to happen?

Avoid exist garbled code.

### How can we reproduce it (as minimally and precisely as possible)?

Ditto.
